path = 'mirrors/private'

[[ref_matchers.rules]]
type = 'regex'
expr = 'refs/heads/.*'
[[ref_matchers.rules]]
type = 'regex'
expr = 'refs/tags/.*'

[source]
type = 'github_authenticated_user'
token_env_var = 'GITHUB_TOKEN'
affiliation = ['owner']
visibility = ['public', 'private']

[[filters]]
type = 'blocklist'
urls = ['https://github.com/DanNixon/not-this-one', 'https://github.com/DanNixon/or-this-one']
